;	ADRESSAGE INDIRECT
;	ADDITION ET STOCKAGE DE DONNE SANS RETOUR DU POINTEUR
	.text
	ldi 10h,AR0		;CHARGER LA VALEUR DE @10H DANS AR0
	ldi *+AR0(0),R0		;CHARGER LA VALEUR DU POITEUR DE L'ADRESSE AR0(0=AR0)(1=11h)DANS R0
	addi *++AR0(10h),R0	;AJOUTER LA VALEUR DE DU POITEUR +10h = 20h EST METTRE LA VALEUR DANS R0
	sti R0,*++AR0(10h)	;STOCKER LA VALEUR DE R0 SUR LA POSITION DU POITEUR 30h(Initial 10h+20h=30h)
	.end